---

version: 2
jobs:
  lint:
    docker:
      - image: canonicalwebteam/dev
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip3 install flake8 black
      - run:
          name: Check syntax with Flake8
          command: flake8
      - run:
          name: Check Black has been run
          command: black --line-length 79 --check
  tests:
    docker:
      - image: canonicalwebteam/dev
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip3 install coverage
      - run:
          name: Run tests with coverage
          command: |
            coverage run  --source canonicalwebteam ./setup.py test
            bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  build:
    jobs:
      - lint
      - tests
